export default [{
          id: 1,
          img:  "./src/assets/katie-zaferes.png",
          star : "./src/assets/star.png",
          rating : "5.0" ,
          reviewCount : "(6)",
          online: "online",
          country: "Usa" ,
          title : "Life lessons with katie Zaferees",
          price : "From $136",
          person :"/ person",
          openSpot: 0
          },      
          {
          id:2,
          img: "./src/assets/mountain-bike.png",
          star : "./src/assets/star.png",
          rating : "5.0" ,
          reviewCount : "(6)",
          online: "online",
          country: "France" ,
          title : "Life lessons with mountain bike",
          price : "From $136",
          person :"/ person",
          openSpot: 12
          },
          {
            id:3,
          img:"./src/assets/wedding-photography.png",
          star : "./src/assets/star.png",
          rating : "5.0" ,
          reviewCount : "(6)",
          online: "online",
          country: "Italy" ,
          title : "Life lessons with wedding photo",
          price : "From $136",
          person :"/ person",
          openSpot: 0
          },
          {
            id: 4,
            img:"./src/assets/pexels-artem-saranin-1202841.jpg",
            star : "./src/assets/star.png",
            rating : "5.0" ,
            reviewCount : "(6)",
            online: "online",
            country: "Italy" ,
            title : "Life lessons with wedding photo",
            price : "From $136",
            person :"/ person",
            openSpot: 24
            },
            {
              id: 5,
              img:"./src/assets/pexels-eberhard-grossgasteiger-2098427.jpg",
              star : "./src/assets/star.png",
              rating : "5.0" ,
              reviewCount : "(6)",
              online: "online",
              country: "Italy" ,
              title : "Life lessons with wedding photo",
              price : "From $136",
              person :"/ person",
              openSpot: 30
              },
              {
                id: 6,
                img:"./src/assets/pexels-james-wheeler-1486974.jpg",
                star : "./src/assets/star.png",
                rating : "5.0" ,
                reviewCount : "(6)",
                online: "online",
                country: "Italy" ,
                title : "Life lessons with wedding photo",
                price : "From $136",
                person :"/ person",
                openSpot: 40
                }
]